import { createContext, useContext, useState, ReactNode } from "react";

type Language = "tr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Settings
    settings: "Ayarlar",
    theme: "Tema",
    language: "Dil",
    light: "Açık",
    dark: "Koyu",
    system: "Sistem",
    turkish: "Türkçe",
    english: "İngilizce",
    themeDescription: "Uygulama temasını seçin",
    languageDescription: "Uygulama dilini seçin",
    appearance: "Görünüm",
    general: "Genel",

    // Navigation
    home: "Ana Sayfa",
    infoCenter: "Bilgi Merkezi",
    appointments: "Randevular",
    medications: "İlaçlar",
    doctors: "Doktorlar",
    doctorsAppointments: "Randevular",
    ecgHistory: "EKG Geçmişi",

    // Header
    appName: "KalpTakip",
    appSubtitle: "Kalp Ritmi Yönetim Sistemi",

    // Dashboard
    currentHeartRate: "Anlık Kalp Atışı",
    normalRange: "Normal aralıkta",
    abnormalRange: "Normal aralığın dışında!",
    dailyAverage: "Günlük Ortalama",
    target: "Hedef",
    weeklyTrend: "Haftalık Trend",
    min: "Min.",
    max: "Maks.",
    mon: "Pzt",
    tue: "Salı",
    wed: "Çar",
    thu: "Per",
    fri: "Cum",
    sat: "Cmt",
    sun: "Paz",
    welcome: "Hoş geldiniz",

    // Heart Rate Anomaly
    heartRateAnomaly: "Kalp Atış Hızı Anomalisi",
    heartRateAnomalyDesc: "Kalp atış hızınız normal değerlerin (60-100 bpm) dışına çıktı. Lütfen dikkatli olun.",
    familyNotified: "Aile üyesine bildirim gönderildi",
    notifiedAt: "Bildirim gönderildi:",

    // Info Center
    infoCenterTitle: "Bilgi Merkezi",
    infoCenterSubtitle: "Kalp ritmi bozuklukları hakkında bilgiler",
    generalInfo: "Genel Bilgi",
    generalInfoShort: "Genel",
    whatIsArrhythmia: "Kalp Ritmi Bozukluğu Nedir?",
    arrhythmiaDesc: "Kalp ritmi bozukluğu (aritmi), kalbinizin çok hızlı, çok yavaş veya düzensiz atmasıdır. Kalp normalde dakikada 60-100 arası atar. Bu aralığın dışındaki atışlar veya düzensiz atışlar aritmi olarak değerlendirilir.",
    importantNote: "Önemli Not:",
    importantNoteDesc: "Her kalp ritmi bozukluğu tehlikeli değildir, ancak bazıları ciddi sağlık sorunlarına yol açabilir. Düzenli takip ve doktor kontrolü önemlidir.",
    aboutQtInterval: "QT Aralığı Hakkında",
    longQtSyndrome: "Uzun QT Sendromu",
    longQtDesc: "Uzun QT sendromu, EKG'de QT aralığının normalden uzun olduğu bir durumdur. Bu durum kalbin elektriksel aktivitesini etkiler ve bazı durumlarda tehlikeli ritim bozukluklarına yol açabilir.",
    shortQtSyndrome: "Kısa QT Sendromu",
    shortQtDesc: "Kısa QT sendromu, EKG'de QT aralığının normalden kısa olduğu nadir bir durumdur. Bu sendrom da kalbin elektriksel aktivitesini etkiler ve atriyal fibrilasyon gibi ritim bozukluklarına yol açabilir.",
    symptoms: "Belirtiler:",
    suddenFainting: "Ani bayılma",
    palpitation: "Çarpıntı hissi",
    seizureLikeAttacks: "Nöbet benzeri ataklar",
    suddenCardiacArrest: "Ani kalp durması riski",
    dizziness: "Baş dönmesi",
    shortnessOfBreath: "Nefes darlığı",
    treatmentManagement: "Tedavi ve Yönetim",
    treatmentDesc: "QT sendromlarının yönetimi kişiye özeldir ve mutlaka bir kardiyolog tarafından planlanmalıdır. Tedavi seçenekleri arasında:",
    drugTherapy: "İlaç tedavisi (Beta-blokerler vb.)",
    lifestyleChanges: "Yaşam tarzı değişiklikleri",
    avoidRiskyDrugs: "Riskli ilaçlardan kaçınma",
    icdImplant: "İmplante edilebilir defibrilatör (ICD) takılması",
    regularCheckup: "Düzenli doktor kontrolü ve EKG takibi",

    // Appointments
    appointmentsTitle: "Randevular",
    appointmentsSubtitle: "Yaklaşan ve geçmiş randevularınız",
    upcomingAppointments: "Yaklaşan Randevular",
    pastAppointments: "Geçmiş Randevular",
    active: "Aktif",
    completed: "Tamamlandı",
    setReminder: "Hatırlatıcı Ayarla",
    cardiology: "Kardiyoloji",

    // Medications - Contraindicated Drugs
    medicationsTitle: "İlaç Uyarıları",
    medicationsSubtitle: "Kullanımı riskli ilaçlar",
    importantWarning: "Önemli Uyarı",
    medicationWarningDesc: "Aşağıdaki ilaçlar kalp ritmi bozukluğu olan hastalar için riskli olabilir. Herhangi bir ilaç kullanmadan önce mutlaka doktorunuza danışın.",
    contraindicatedDrugs: "Riskli İlaçlar",
    drugsShort: "İlaçlar",
    contraindicatedDrugsTitle: "Kullanılmaması Gereken İlaçlar",
    contraindicatedDrugsDesc: "Kalp ritim bozukluğu olan kişilerin aşağıdaki ilaç gruplarını kullanmaması veya doktor gözetiminde dikkatli kullanması gerekmektedir. Bu ilaçlar QT aralığını uzatabilir veya kalp ritmi üzerinde olumsuz etkiler yaratabilir.",
    high: "Yüksek",
    mediumHigh: "Orta-Yüksek",
    medium: "Orta",
    reason: "Sebep:",
    reminder: "Hatırlatma:",
    reminderItem1: "Yeni bir ilaç başlamadan önce doktorunuza mutlaka bildirin",
    reminderItem2: "Reçetesiz ilaçlar bile risk oluşturabilir",
    reminderItem3: "Bu liste tüm riskli ilaçları içermeyebilir",
    reminderItem4: "İlaç etkileşimleri kişiye göre değişebilir",
    macrolideAntibiotics: "Makrolid Antibiyotikler",
    antiarrhythmicDrugs: "Antiaritmik İlaçlar",
    antipsychoticDrugs: "Antipsikotik İlaçlar",
    someAntidepressants: "Bazı Antidepresanlar",
    antihistamines: "Antihistaminikler",
    antimalarialDrugs: "Antimalaryal İlaçlar",
    mayExtendQt: "QT aralığını uzatabilir",
    directHeartEffect: "Kalp ritmi üzerinde direkt etki",
    qtExtensionRisk: "QT uzaması riski",
    highDoseQtExtension: "Yüksek dozlarda QT uzaması",
    cardiacSideEffects: "Kardiyak yan etkiler",
    qtIntervalEffects: "QT aralığı etkileri",

    // Medication Reminders
    medReminders: "İlaç Hatırlatma",
    remindersShort: "Hatırlatma",
    addMedReminder: "İlaç Hatırlatması Ekle",
    medicationName: "İlaç Adı",
    medNamePlaceholder: "örn: Metoprolol",
    medicationTime: "İlaç Saati",
    remindBefore: "Kaç Dakika Önce Hatırlat",
    minutes: "dakika",
    addReminder: "Hatırlatma Ekle",
    activeReminders: "Aktif Hatırlatmalar",
    noReminders: "Henüz hatırlatma eklenmemiş",
    reminderAdded: "Hatırlatma eklendi!",
    reminderRemoved: "Hatırlatma silindi",
    minBefore: "dk önce",
    medicationReminder: "İlaç Hatırlatması",
    minutesBefore: "dakika sonra ilaç saati",
    timeToTakeMed: "İlaç alma zamanı",

    // Doctors
    doctorsTitle: "Kardiyoloji Uzmanları",
    doctorsSubtitle: "Kalp ritmi bozuklukları konusunda uzman doktorlar",
    experience: "Deneyim:",
    bookAppointment: "Randevu Al",
    aboutAppointment: "Randevu Hakkında",
    appointmentInfo: "Randevu almak için doktor kartında bulunan \"Randevu Al\" butonuna tıklayabilir veya doğrudan hastane telefon numarasını arayabilirsiniz.",
    years: "yıl",
    electrophysiology: "Elektrofizyoloji",
    arrhythmiaPacemaker: "Aritmi ve Pacemaker",
    invasiveElectrophysiology: "İnvaziv Elektrofizyoloji",
    heartRhythmDisorders: "Kalp Ritmi Bozuklukları",

    // Booking
    selectDateTime: "Tarih ve Saat Seçin",
    selectDate: "Tarih Seçin",
    selectTime: "Saat Seçin",
    availableTimes: "Uygun Saatler",
    confirmBooking: "Randevuyu Onayla",
    cancel: "İptal",
    bookingSuccess: "Randevu başarıyla oluşturuldu!",
    appointmentWith: "Randevunuz:",

    // Medication Reminders
    medRemindersTitle: "İlaç Hatırlatıcı",
    medRemindersSubtitle: "İlaçlarınızı takip edin ve hatırlatıcı ayarlayın",
    myMedications: "İlaçlarım",
    medHistory: "Geçmiş",
    addMedication: "İlaç Ekle",
    editMedication: "İlaç Düzenle",
    medName: "İlaç Adı",
    medDosage: "Dozaj",
    medDosagePlaceholder: "Örn: 50mg",
    medNotes: "Notlar",
    medNotesPlaceholder: "Ek notlar...",
    reminderTimes: "Hatırlatma Saatleri",
    addTime: "Saat Ekle",
    todaySchedule: "Bugünün Programı",
    taken: "Alındı",
    skipped: "Atlandı",
    markedTaken: "Alındı olarak işaretlendi",
    markedSkipped: "Atlandı olarak işaretlendi",
    medAdded: "İlaç eklendi",
    medUpdated: "İlaç güncellendi",
    medDeleted: "İlaç silindi",
    noMedications: "Henüz ilaç eklenmedi. Yukarıdaki butona tıklayarak başlayın.",
    noHistory: "Henüz kayıt yok.",
    save: "Kaydet",
    reminderSet: "Hatırlatıcı ayarlandı",
    reminderSetDesc: "dakika önce bildirim alacaksınız",
    notificationsEnabled: "Bildirimler etkinleştirildi",
    notificationsDenied: "Bildirim izni reddedildi. Tarayıcı ayarlarından etkinleştirin.",

    // ECG History
    ecgHistoryTitle: "EKG Geçmişi",
    ecgHistorySubtitle: "EKG kayıtlarınızı PDF veya fotoğraf olarak yükleyin",
    totalEcg: "Toplam EKG",
    lastQt: "Son QT",
    lastUpload: "Son Yükleme",
    ecgRecord: "EKG Kaydı",
    normal: "Normal",
    mildExtension: "Hafif Uzama",
    date: "Tarih",
    time: "Saat",
    qtInterval: "QT Aralığı",
    heartRate: "Kalp Atışı",
    doctor: "Doktor",
    notes: "Notlar:",
    downloadEcgReport: "EKG Raporunu İndir",
    uploadEcg: "EKG Kaydı Yükle",
    uploadEcgDesc: "PDF veya fotoğraf formatında EKG kayıtlarınızı yükleyin",
    selectFile: "Dosya Seç",
    fileUploaded: "Dosya başarıyla yüklendi!",
    invalidFileType: "Geçersiz dosya türü. PDF veya resim dosyası seçin.",
    fileTooLarge: "Dosya boyutu çok büyük (max 10MB)",
    recordDeleted: "Kayıt silindi",
    noEcgRecords: "Henüz EKG kaydı yüklenmemiş",
    noRecords: "Kayıt yok",
    imageFile: "Fotoğraf",

    // Auth - Landing
    createAccount: "Hesap Oluştur",
    loginButton: "Giriş Yap",
    aboutApp: "Uygulama Hakkında",
    aboutAppDesc: "KalpTakip, kalp ritmi bozukluğu olan hastaların sağlık durumlarını takip etmelerine, ilaç hatırlatmaları almalarına ve EKG kayıtlarını yönetmelerine yardımcı olan kapsamlı bir mobil sağlık uygulamasıdır.",
    aboutFeature1: "Kalp atışı takibi",
    aboutFeature2: "Anomali bildirimleri",
    aboutFeature3: "EKG kayıt yönetimi",
    aboutFeature4: "İlaç hatırlatmaları",

    // Auth - Register
    personalInfo: "Kişisel Bilgiler",
    firstName: "Ad",
    firstNamePlaceholder: "Adınızı girin",
    lastName: "Soyad",
    lastNamePlaceholder: "Soyadınızı girin",
    phoneNumber: "Telefon Numarası",
    password: "Şifre",
    passwordPlaceholder: "Minimum 8 karakter",
    confirmPassword: "Şifre Doğrulama",
    confirmPasswordPlaceholder: "Şifrenizi tekrar girin",
    fieldRequired: "Bu alan zorunludur",
    invalidPhone: "Geçerli bir telefon numarası girin",
    passwordMinLength: "Şifre en az 8 karakter olmalıdır",
    passwordMismatch: "Şifreler eşleşmiyor",
    registerSuccess: "Hesap başarıyla oluşturuldu!",
    phoneAlreadyExists: "Bu telefon numarası zaten kayıtlı",
    alreadyHaveAccount: "Zaten hesabınız var mı?",
    back: "Geri",

    // Auth - Login
    loginInfo: "Giriş Bilgileri",
    fillAllFields: "Lütfen tüm alanları doldurun",
    invalidCredentials: "Telefon numarası veya şifre hatalı",
    loginSuccess: "Giriş başarılı!",
    noAccount: "Hesabınız yok mu?",

    // Settings - Family Member
    defineFamilyMember: "Aile Üyesi Tanımla",
    familyMemberDesc: "Anomali durumunda bilgilendirilecek aile üyesini tanımlayın",
    familyMemberName: "Aile Üyesi Adı",
    familyNamePlaceholder: "Ad Soyad",
    familyMemberPhone: "Telefon Numarası",
    anomalyNotification: "Anomali Bildirimi Gönder",
    saveFamilyMember: "Kaydet",
    familySaved: "Aile üyesi bilgileri kaydedildi!",

    // Logout
    logout: "Oturumu Kapat",
    logoutSuccess: "Oturum kapatıldı",

    // BeatWise Device
    beatWiseDevice: "BeatWise Cihazı",
    bluetoothNotAvailable: "Web Bluetooth bu tarayıcıda kullanılamıyor. BeatWise-S3 cihazınızı bağlamak için bu sayfayı Android'de Chrome veya Edge ile açın.",
    statusIdle: "Bağlantı Yok",
    statusConnecting: "Bağlanıyor…",
    statusConnected: "Bağlandı",
    statusDisconnected: "Bağlantı Kesildi",
    statusError: "Hata",
    connectDevice: "Cihazı Bağla",
    disconnectDevice: "Bağlantıyı Kes",
    scanning: "Taranıyor…",
    bpmLabel: "NABIZ",
    accelLabel: "İVME (mg)",
    fingerLabel: "PARMAK",
    yes: "Evet",
    no: "Hayır",
  },
  en: {
    // Settings
    settings: "Settings",
    theme: "Theme",
    language: "Language",
    light: "Light",
    dark: "Dark",
    system: "System",
    turkish: "Turkish",
    english: "English",
    themeDescription: "Select application theme",
    languageDescription: "Select application language",
    appearance: "Appearance",
    general: "General",

    // Navigation
    home: "Home",
    infoCenter: "Info Center",
    appointments: "Appointments",
    medications: "Medications",
    doctors: "Doctors",
    doctorsAppointments: "Doctors & Appointments",
    ecgHistory: "ECG History",

    // Header
    appName: "HeartTrack",
    appSubtitle: "Heart Rhythm Management System",

    // Dashboard
    currentHeartRate: "Current Heart Rate",
    normalRange: "Within normal range",
    abnormalRange: "Outside normal range!",
    dailyAverage: "Daily Average",
    target: "Target",
    weeklyTrend: "Weekly Trend",
    min: "Min.",
    max: "Max.",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    welcome: "Welcome",

    // Heart Rate Anomaly
    heartRateAnomaly: "Heart Rate Anomaly",
    heartRateAnomalyDesc: "Your heart rate has gone outside normal values (60-100 bpm). Please be careful.",
    familyNotified: "Family member notified",
    notifiedAt: "Notification sent to:",

    // Info Center
    infoCenterTitle: "Info Center",
    infoCenterSubtitle: "Information about heart rhythm disorders",
    generalInfo: "General Info",
    generalInfoShort: "General",
    whatIsArrhythmia: "What is Heart Rhythm Disorder?",
    arrhythmiaDesc: "Heart rhythm disorder (arrhythmia) is when your heart beats too fast, too slow, or irregularly. The heart normally beats 60-100 times per minute. Beats outside this range or irregular beats are considered arrhythmia.",
    importantNote: "Important Note:",
    importantNoteDesc: "Not all heart rhythm disorders are dangerous, but some can lead to serious health problems. Regular monitoring and doctor check-ups are important.",
    aboutQtInterval: "About QT Interval",
    longQtSyndrome: "Long QT Syndrome",
    longQtDesc: "Long QT syndrome is a condition where the QT interval on the ECG is longer than normal. This condition affects the heart's electrical activity and can lead to dangerous rhythm disorders in some cases.",
    shortQtSyndrome: "Short QT Syndrome",
    shortQtDesc: "Short QT syndrome is a rare condition where the QT interval on the ECG is shorter than normal. This syndrome also affects the heart's electrical activity and can lead to rhythm disorders such as atrial fibrillation.",
    symptoms: "Symptoms:",
    suddenFainting: "Sudden fainting",
    palpitation: "Palpitations",
    seizureLikeAttacks: "Seizure-like attacks",
    suddenCardiacArrest: "Risk of sudden cardiac arrest",
    dizziness: "Dizziness",
    shortnessOfBreath: "Shortness of breath",
    treatmentManagement: "Treatment and Management",
    treatmentDesc: "Management of QT syndromes is personalized and must be planned by a cardiologist. Treatment options include:",
    drugTherapy: "Drug therapy (Beta-blockers, etc.)",
    lifestyleChanges: "Lifestyle changes",
    avoidRiskyDrugs: "Avoiding risky medications",
    icdImplant: "Implantable cardioverter-defibrillator (ICD) implantation",
    regularCheckup: "Regular doctor check-ups and ECG monitoring",

    // Appointments
    appointmentsTitle: "Appointments",
    appointmentsSubtitle: "Your upcoming and past appointments",
    upcomingAppointments: "Upcoming Appointments",
    pastAppointments: "Past Appointments",
    active: "Active",
    completed: "Completed",
    setReminder: "Set Reminder",
    cardiology: "Cardiology",

    // Medications - Contraindicated Drugs
    medicationsTitle: "Medication Warnings",
    medicationsSubtitle: "Risky medications",
    importantWarning: "Important Warning",
    medicationWarningDesc: "The following medications may be risky for patients with heart rhythm disorders. Always consult your doctor before using any medication.",
    contraindicatedDrugs: "Risky Drugs",
    drugsShort: "Drugs",
    contraindicatedDrugsTitle: "Contraindicated Medications",
    contraindicatedDrugsDesc: "People with heart rhythm disorders should avoid or use the following drug groups with caution under medical supervision. These drugs may extend the QT interval or have adverse effects on heart rhythm.",
    high: "High",
    mediumHigh: "Medium-High",
    medium: "Medium",
    reason: "Reason:",
    reminder: "Reminder:",
    reminderItem1: "Always inform your doctor before starting a new medication",
    reminderItem2: "Even over-the-counter medications can pose risks",
    reminderItem3: "This list may not include all risky medications",
    reminderItem4: "Drug interactions can vary from person to person",
    macrolideAntibiotics: "Macrolide Antibiotics",
    antiarrhythmicDrugs: "Antiarrhythmic Drugs",
    antipsychoticDrugs: "Antipsychotic Drugs",
    someAntidepressants: "Some Antidepressants",
    antihistamines: "Antihistamines",
    antimalarialDrugs: "Antimalarial Drugs",
    mayExtendQt: "May extend QT interval",
    directHeartEffect: "Direct effect on heart rhythm",
    qtExtensionRisk: "QT extension risk",
    highDoseQtExtension: "QT extension at high doses",
    cardiacSideEffects: "Cardiac side effects",
    qtIntervalEffects: "QT interval effects",

    // Medication Reminders
    medReminders: "Med Reminders",
    remindersShort: "Reminders",
    addMedReminder: "Add Medication Reminder",
    medicationName: "Medication Name",
    medNamePlaceholder: "e.g: Metoprolol",
    medicationTime: "Medication Time",
    remindBefore: "Remind Before (minutes)",
    minutes: "minutes",
    addReminder: "Add Reminder",
    activeReminders: "Active Reminders",
    noReminders: "No reminders added yet",
    reminderAdded: "Reminder added!",
    reminderRemoved: "Reminder removed",
    minBefore: "min before",
    medicationReminder: "Medication Reminder",
    minutesBefore: "minutes until medication time",
    timeToTakeMed: "Time to take medication",

    // Doctors
    doctorsTitle: "Cardiology Specialists",
    doctorsSubtitle: "Expert doctors in heart rhythm disorders",
    experience: "Experience:",
    bookAppointment: "Book Appointment",
    aboutAppointment: "About Appointments",
    appointmentInfo: "To book an appointment, you can click the \"Book Appointment\" button on the doctor card or call the hospital phone number directly.",
    years: "years",
    electrophysiology: "Electrophysiology",
    arrhythmiaPacemaker: "Arrhythmia and Pacemaker",
    invasiveElectrophysiology: "Invasive Electrophysiology",
    heartRhythmDisorders: "Heart Rhythm Disorders",

    // Booking
    selectDateTime: "Select Date and Time",
    selectDate: "Select Date",
    selectTime: "Select Time",
    availableTimes: "Available Times",
    confirmBooking: "Confirm Booking",
    cancel: "Cancel",
    bookingSuccess: "Appointment booked successfully!",
    appointmentWith: "Your appointment:",

    // Medication Reminders
    medRemindersTitle: "Medication Reminders",
    medRemindersSubtitle: "Track your medications and set reminders",
    myMedications: "My Medications",
    medHistory: "History",
    addMedication: "Add Medication",
    editMedication: "Edit Medication",
    medName: "Medication Name",
    medDosage: "Dosage",
    medDosagePlaceholder: "e.g. 50mg",
    medNotes: "Notes",
    medNotesPlaceholder: "Additional notes...",
    reminderTimes: "Reminder Times",
    addTime: "Add Time",
    todaySchedule: "Today's Schedule",
    taken: "Taken",
    skipped: "Skipped",
    markedTaken: "Marked as taken",
    markedSkipped: "Marked as skipped",
    medAdded: "Medication added",
    medUpdated: "Medication updated",
    medDeleted: "Medication deleted",
    noMedications: "No medications added yet. Click the button above to start.",
    noHistory: "No history yet.",
    save: "Save",
    reminderSet: "Reminder set",
    reminderSetDesc: "You'll be notified minutes before",
    notificationsEnabled: "Notifications enabled",
    notificationsDenied: "Notification permission denied. Enable from browser settings.",

    // ECG History
    ecgHistoryTitle: "ECG History",
    ecgHistorySubtitle: "Upload your ECG records as PDF or photo",
    totalEcg: "Total ECG",
    lastQt: "Last QT",
    lastUpload: "Last Upload",
    ecgRecord: "ECG Record",
    normal: "Normal",
    mildExtension: "Mild Extension",
    date: "Date",
    time: "Time",
    qtInterval: "QT Interval",
    heartRate: "Heart Rate",
    doctor: "Doctor",
    notes: "Notes:",
    downloadEcgReport: "Download ECG Report",
    uploadEcg: "Upload ECG Record",
    uploadEcgDesc: "Upload your ECG records in PDF or photo format",
    selectFile: "Select File",
    fileUploaded: "File uploaded successfully!",
    invalidFileType: "Invalid file type. Select a PDF or image file.",
    fileTooLarge: "File size too large (max 10MB)",
    recordDeleted: "Record deleted",
    noEcgRecords: "No ECG records uploaded yet",
    noRecords: "No records",
    imageFile: "Photo",

    // Auth - Landing
    createAccount: "Create Account",
    loginButton: "Login",
    aboutApp: "About the App",
    aboutAppDesc: "HeartTrack is a comprehensive mobile health application that helps patients with heart rhythm disorders track their health, receive medication reminders, and manage their ECG records.",
    aboutFeature1: "Heart rate tracking",
    aboutFeature2: "Anomaly notifications",
    aboutFeature3: "ECG record management",
    aboutFeature4: "Medication reminders",

    // Auth - Register
    personalInfo: "Personal Information",
    firstName: "First Name",
    firstNamePlaceholder: "Enter your first name",
    lastName: "Last Name",
    lastNamePlaceholder: "Enter your last name",
    phoneNumber: "Phone Number",
    password: "Password",
    passwordPlaceholder: "Minimum 8 characters",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Re-enter your password",
    fieldRequired: "This field is required",
    invalidPhone: "Enter a valid phone number",
    passwordMinLength: "Password must be at least 8 characters",
    passwordMismatch: "Passwords do not match",
    registerSuccess: "Account created successfully!",
    phoneAlreadyExists: "This phone number is already registered",
    alreadyHaveAccount: "Already have an account?",
    back: "Back",

    // Auth - Login
    loginInfo: "Login Information",
    fillAllFields: "Please fill in all fields",
    invalidCredentials: "Invalid phone number or password",
    loginSuccess: "Login successful!",
    noAccount: "Don't have an account?",

    // Settings - Family Member
    defineFamilyMember: "Define Family Member",
    familyMemberDesc: "Define a family member to be notified in case of anomaly",
    familyMemberName: "Family Member Name",
    familyNamePlaceholder: "Full Name",
    familyMemberPhone: "Phone Number",
    anomalyNotification: "Send Anomaly Notification",
    saveFamilyMember: "Save",
    familySaved: "Family member info saved!",

    // Logout
    logout: "Logout",
    logoutSuccess: "Logged out successfully",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("kalptakip-language");
    return (stored as Language) || "tr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("kalptakip-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
